version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${pwd}
      POSTGRES_USER: ${username}
      POSTGRES_DB: ${database}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  telegram_bot:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
